### ISSUE TITLE
Not compatible with Laravel >= 5.4.23 (\Illuminate\Foundation\Application::share removed)

### ISSUE THREAD

**Issue by Glutexo** [Snowfire/Laravel-Postmark-Driver#11]
Hi!

This driver does not work with Laravel versions >= 5.4.23. It is because method `\Illuminate\Foundation\Application::share` has been removed in favor of `singleton` method. See https://github.com/laravel/framework/commit/1a1969b6e6f793c3b2a479362641487ee9cbf736.

I hotfixed this by replacing by changing its usage on the _line no. 36_ of the file _PostmarkServiceProvider.php_, which was

```php
$this->app['swift.mailer'] = $this->app->share(function ($app) use ($postmark) {
```

to

```php
$this->app->singleton('swift.mailer', function ($app) use ($postmark) {
```

However, I can’t guarantee that this solution doesn’t break anything or that there aren’t any more incompatibilities.

**Comment by emilsundberg** [comment]
Solved in #12
