### ISSUE TITLE
dev-master / L4 branch still requires L5

### ISSUE THREAD

**Issue by envision** [Snowfire/Laravel-Postmark-Driver#8]
There is something wrong with this L4 branch or docs as I have included "snowfire/mail": "dev-master" to composer.json and ran composer update, got a problem scenario. This package has been working for quite a while without composer update.

snowfire/mail dev-master requires illuminate/support 5.* -> satisfiable, by laravel/framework[5.1.x-dev], illuminate/support[5.0.x-dev, 5.1.x-dev, 5.2. x-dev, v5.0.0, v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.0.4, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.6, v5.1.8].

**Comment by emilsundberg** [comment]
Yes you are right, L4 readme should not say dev-master. Try to use this in your composer.json:

```
"snowfire/mail": "dev-laravel-4",
```

**Comment by seanfahey** [comment]
Thanks @emilsundberg :+1:
